/*
 * common.js - common wormhole functions
 * Copyright (c) 2018-2019 Jonathan Gonzalez (MIT License).
 */

'use strict';

const assert = require('bsert');

exports.types = {
  SIMPLE_SEND: 0x00,
  BUY_TOKEN: 0x01,
  RESTRICTED_SEND: 0x02,
  SEND_TO_OWNERS: 0x03,
  SEND_ALL: 0x04,
  SAVINGS_MARK: 0x0a,
  SAVINGS_COMPROMISED: 0x0b,
  AUTOMATIC_DISPENSARY: 0x0f,
  TRADE_OFFER: 0x14,
  ACCEPT_OFFER_BCH: 0x16,
  METADEX_TRADE: 0x19,
  METADEX_TRADE_CANCEL_PRICE: 0x1a,
  METADEX_TRADE_CACNEL_PAIR: 0x1b,
  METADEX_TRADE_CANCEL_ECOSYSTEM: 0x1c,
  NOTIFICATION: 0x1f,
  OFFER_ACCEPT_BET: 0x28,
  CREATE_PROPERTY_FIXED: 0x32,
  CREATE_PROPERTY_VARIABLE: 0x33,
  PROMOTE_PROPERTY: 0x34,
  CLOSE_CROWDSALE: 0x35,
  CREATE_PROPERTY_MANUAL: 0x36,
  GRANT_PROPERTY_TOKENS: 0x37,
  REVOKE_PROPERTY_TOKENS: 0x38,
  GET_BASE_PROPERTY: 0x44,
  CHANGE_ISSUER_ADDRESS: 0x46,
  ENABLE_FREEZING: 0x47,
  DISABLE_FREEZING: 0x48,
  FREEZE_PROPERTY_TOKENS: 0xb9,
  UNFREEZE_PROPERTY_TOKENS: 0xba,
  DEACTIVATION: 0xfffd,
  ACTIVATION: 0xfffe,
  ALERT: 0xffff

};

exports.typesByVal = {
  0x00: 'SIMPLE_SEND',
  0x01: 'BUY_TOKEN',
  0x02: 'RESTRICTED_SEND',
  0x03: 'SEND_TO_OWNERS',
  0x04: 'SEND_ALL',
  0x0a: 'SAVINGS_MARK',
  0x0b: 'SAVINGS_COMPROMISED',
  0x0f: 'AUTOMATIC_DISPENSARY',
  0x14: 'TRADE_OFFER',
  0x16: 'ACCEPT_OFFER_BCH',
  0x19: 'METADEX_TRADE',
  0x1a: 'METADEX_TRADE_CANCEL_PRICE',
  0x1b: 'METADEX_TRADE_CANCEL_PAIR',
  0x1c: 'METADEX_TRADE_CANCEL_ECOSYSTEM',
  0x1f: 'NOTIFICATION',
  0x28: 'OFFER_ACCEPT_BET',
  0x32: 'CREATE_PROPERTY_FIXED',
  0x33: 'CREATE_PROPERTY_VARIABLE',
  0x34: 'PROMOTE_PROPERTY',
  0x35: 'CLOSE_CROWDSALE',
  0x36: 'CREATE_PROPERTY_MANUAL',
  0x37: 'GRANT_PROPERTY_TOKENS',
  0x38: 'REVOKE_PROPERTY_TOKENS',
  0x44: 'GET_BASE_PROPERTY',
  0x46: 'CHANGE_ISSUER_ADDRESS',
  0x47: 'ENABLE_FREEZING',
  0x48: 'DISABLE_FREEZING',
  0xb9: 'FREEZE_PROPERTY_TOKENS',
  0xba: 'UNFREEZE_PROPERTY_TOKENS',
  0xfffd: 'DEACTIVATION',
  0xfffe: 'ACTIVATION',
  0xffff: 'ALERT'
};

